[phases.setup]
nixPkgs = [
  'php83',
  'php83Extensions.gd',
  'php83Extensions.pdo',
  'php83Extensions.pdo_mysql',
  'php83Extensions.mbstring',
  'php83Extensions.xml',
  'php83Extensions.zip',
  'php83Extensions.bcmath'
]

[phases.install]
cmds = ['composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-gd']